### ISSUE TITLE
something broke after 3.3.62

### ISSUE THREAD

**Issue by cecgeology** [opengisch/quick_attribution#5]
I've been using the nightly dev release for QGIS 3.3 and something after 3.3.62 changed in a way that this plugin crashed out when it tries to load my project file. Project works fine without the plugin enabled

h2. User Feedback

I have a project that cannot open in versions of the nightly build greater than 3.3.62
The last thing shown on the bottom as to what layer is being loaded is a tif file
I removed that layer (in v3.2.2) and it hangs on the next layer, also a tif.
I then removed all the raster layers from the project and it still hangs.
Tried saving as qgs and qgz with same results.
Then removed layer by layer (and some groups of layers) and got a crash each iteration.
I also removed all layouts.
Once all layers were removed, leaving just an empty group, it ceased to crash.
Then finally I remembered to disable all plugins and it loaded fine. 
It seems the plugin is called "quick attribution"
h2. Report Details

*Crash ID*: dc2189f6055ad87c791ac1958107a7e98363e414

*Stack Trace*
<pre>
QgsRunProcess::processExit :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QMetaObject::activate :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QItemSelectionModel::select :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QMetaObject::activate :
PyInit_QtCore :
PyInit_QtCore :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QgsCredentialDialog::leMasterPassVerify_textChanged :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QMetaObject::activate :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QMetaObject::activate :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsRunProcess::processExit :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
QMetaObject::activate :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRunProcess::processExit :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRunProcess::processExit :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsLayerStylingWidget::~QgsLayerStylingWidget :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.3.0-Master
QGIS code revision: commit:69a5de1cdb
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by m-kuhn** [comment]
Thanks for the report.

Are you still able to open the feature form and the attribute table or does it crash as well? I have just heard of a similar issue but unrelated to this plugin.

**Comment by m-kuhn** [comment]
Sidenote -> can you install the `qgis-nightly-pdb` package? The stack trace information will be much better.

**Comment by cecgeology** [comment]
> Thanks for the report.
> 
> Are you still able to open the feature form and the attribute table or does it crash as well? I have just heard of a similar issue but unrelated to this plugin.

Yes, both those open provided this plugin is not enabled
Another thing is the plugin will open and run fine provided the project is opened first. Its almost like it tries to get an attribute list for layers as they load and maybe some that are read only or images are creating an issue with the plugin

**Comment by cecgeology** [comment]
> Sidenote -> can you install the `qgis-nightly-pdb` package? The stack trace information will be much better.

h2. User Feedback

Quick Attribution Enabled

h2. Report Details

*Crash ID*: 58df690b71e5d11789ebe8f72f3912aeb9be5982


*Stack Trace*
<pre>
QgsMapLayer::flags qgsmaplayer.cpp:149
QgisApp::legendLayerSelectionChanged qgisapp.cpp:12059
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgisApp::*)(void) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgisApp::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgisApp::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QItemSelectionModel::select :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsLayerTreeView::setCurrentLayer qgslayertreeview.cpp:117
QgisApp::setActiveLayer qgisapp.cpp:10576
QgisAppInterface::setActiveLayer qgisappinterface.cpp:188
QgisInterface::qt_static_metacall moc_qgisinterface.cpp:487
QMetaObject::activate :
PyInit_QtCore :
PyInit_QtCore :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QgsMapLayerComboBox::layerChanged moc_qgsmaplayercombobox.cpp:205
QgsMapLayerComboBox::rowsChanged qgsmaplayercombobox.cpp:133
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsMapLayerComboBox::*)(void) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgsMapLayerComboBox::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgsMapLayerComboBox::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRole :
QSortFilterProxyModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers qgsmaplayermodel.cpp:171
QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void,void (__cdecl QgsMapLayerModel::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgsMapLayerModel::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64>::call<QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgsMapLayerModel::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64,QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QgsProject::layersAdded moc_qgsproject.cpp:1025
QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void,void (__cdecl QgsProject::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgsProject::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64>::call<QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgsProject::*)(QList<QgsMapLayer * __ptr64> const & __ptr64) __ptr64,QtPrivate::List<QList<QgsMapLayer * __ptr64> const & __ptr64>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QgsMapLayerStore::layersAdded moc_qgsmaplayerstore.cpp:315
QgsMapLayerStore::addMapLayers qgsmaplayerstore.cpp:80
QgsProject::addMapLayers qgsproject.cpp:2645
QgsProject::addLayer qgsproject.cpp:941
QgsProject::_getMapLayers qgsproject.cpp:878
QgsProject::readProjectFile qgsproject.cpp:1228
QgsProject::unzip qgsproject.cpp:2574
QgsProject::read qgsproject.cpp:993
QgsProject::read qgsproject.cpp:960
QgisApp::addProject qgisapp.cpp:5677
QgisApp::openProject qgisapp.cpp:6088
QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<QAction * __ptr64>,void,void (__cdecl QgisApp::*)(QAction * __ptr64) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgisApp::*)(QAction * __ptr64) __ptr64>::call<QtPrivate::List<QAction * __ptr64>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgisApp::*)(QAction * __ptr64) __ptr64,QtPrivate::List<QAction * __ptr64>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QMenu::~QMenu :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:347
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:347
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1499
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.3.0-Master
QGIS code revision: commit:cb0b335a95
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by m-kuhn** [comment]
Pull request on QGIS pending review
